name: online_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  scoped_model: ^2.0.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
